─ ZSU.PMA.UUE (2:5021/2.30) ───────────────────────────────────── ZSU.PMA.UUE ─
 Msg  : 2 of 120
 From : Igor Konev                          2:5077/27.11    21 Jul 97  01:15:00
 To   : All                                                 22 Jul 97  18:13:59
 Subj : Interpolation with Lagrange and Newton methods
───────────────────────────────────────────────────────────────────────────────
  Hi, All!

    Вот обещанная прога интерполяции по Лагранжу и Ньютону.
Вызов:
     interpol <filename>

например: interpol interpol.dat

В текстовый файл .dat заносятся пары координат X Y всех точек.

---
 * Origin: Таверна 'Лошадиный ботинок' (2:5077/27.11)

